_format_version: "3.0"
_transform: false
consumers:
  - username: token_server
    id: f85447cf-124c-4d29-a70d-b6b1024a47ef
    tags:
      - jwt
      - token
    custom_id: ~
    created_at: 1754143539
    updated_at: 1754143539
parameters:
  - key: cluster_id
    created_at: ~
    value: dadf5c95-c531-473e-abe9-46affbc30868
services:
  - write_timeout: 60000
    connect_timeout: 60000
    name: booking-service
    read_timeout: 60000
    created_at: 1753945980
    updated_at: 1753946019
    retries: 5
    id: 0929d3ca-7920-4c59-885f-7627bb7b751c
    port: 8084
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: ~
    tags:
      - booking
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: chatbot-service
    read_timeout: 60000
    created_at: 1753946346
    updated_at: 1753946346
    retries: 5
    id: 61d2a659-5240-4b05-b070-8890526290b5
    port: 5000
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: ~
    tags:
      - chatbot
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: auth-service
    read_timeout: 60000
    created_at: 1753945890
    updated_at: 1754142832
    retries: 5
    id: 70358580-7171-41af-8996-1a0bc9582e9a
    port: 8081
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: /api/auth
    tags:
      - auth
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: cms-service
    read_timeout: 60000
    created_at: 1753946045
    updated_at: 1754142650
    retries: 5
    id: a2320f4b-c669-4103-b066-d66b3110e1b3
    port: 8086
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: /api/layouts
    tags:
      - cms
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: authorization-service
    read_timeout: 60000
    created_at: 1753945738
    updated_at: 1753945738
    retries: 5
    id: b117b3f7-e708-448e-981a-95dff30b577c
    port: 8082
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: ~
    tags:
      - authorization
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: payment-service
    read_timeout: 60000
    created_at: 1753946188
    updated_at: 1753946188
    retries: 5
    id: b3842a14-c43b-43ee-bf67-9b91552d5bf4
    port: 8085
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: ~
    tags:
      - payment
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: user-service
    read_timeout: 60000
    created_at: 1753945941
    updated_at: 1753945941
    retries: 5
    id: d40c7848-7417-4df7-8146-ced83c62ab96
    port: 8080
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: ~
    tags:
      - user
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: handlefiles-service
    read_timeout: 60000
    created_at: 1753946142
    updated_at: 1753946142
    retries: 5
    id: d465774d-fd1d-4aea-9043-7b4213602225
    port: 8087
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: ~
    tags:
      - handlefiles
      - api-backend
  - write_timeout: 60000
    connect_timeout: 60000
    name: hotel-service
    read_timeout: 60000
    created_at: 1753956609
    updated_at: 1754142091
    retries: 5
    id: f2bfbbf7-f020-432b-b33f-33cad7554524
    port: 8083
    ca_certificates: ~
    tls_verify: ~
    enabled: true
    tls_verify_depth: ~
    host: host.docker.internal
    protocol: http
    client_certificate: ~
    path: /api/hotels
    tags:
      - hotel
      - api-backend
routes:
  - destinations: ~
    protocols:
      - http
      - https
    service: 61d2a659-5240-4b05-b070-8890526290b5
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753946362
    updated_at: 1754142381
    id: 32854a63-b5c0-4b19-a30c-c0f0a36a73da
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/chat-bot
    regex_priority: 0
    headers: ~
    sources: ~
    name: chatbot-route
    snis: ~
    tags:
      - chatbot
  - destinations: ~
    protocols:
      - http
      - https
    service: b117b3f7-e708-448e-981a-95dff30b577c
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753945769
    updated_at: 1754142411
    id: 4b043e0c-0bb2-4ef9-ad77-0c1fb56f5bea
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/authorization
    regex_priority: 0
    headers: ~
    sources: ~
    name: authorization-route
    snis: ~
    tags:
      - authorization
  - destinations: ~
    protocols:
      - http
      - https
    service: f2bfbbf7-f020-432b-b33f-33cad7554524
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753956628
    updated_at: 1754142337
    id: 5e0e3004-3248-4e4c-adb6-fc8184ba3b12
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/hotels
    regex_priority: 0
    headers: ~
    sources: ~
    name: hotel-route
    snis: ~
    tags:
      - hotel
  - destinations: ~
    protocols:
      - http
      - https
    service: b3842a14-c43b-43ee-bf67-9b91552d5bf4
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753946201
    updated_at: 1754142426
    id: a6d520f6-9521-4464-858a-35e83946927a
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/payment
    regex_priority: 0
    headers: ~
    sources: ~
    name: payment-route
    snis: ~
    tags:
      - payment
  - destinations: ~
    protocols:
      - http
      - https
    service: d40c7848-7417-4df7-8146-ced83c62ab96
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753945958
    updated_at: 1754142436
    id: bd12131b-b47d-4992-aa3a-ea96a351fc73
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/user
    regex_priority: 0
    headers: ~
    sources: ~
    name: user-route
    snis: ~
    tags:
      - user
  - destinations: ~
    protocols:
      - http
      - https
    service: d465774d-fd1d-4aea-9043-7b4213602225
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753946158
    updated_at: 1754142445
    id: bdaeb52a-53cf-409c-aa23-5aa2d9bc4d61
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/handlefile
    regex_priority: 0
    headers: ~
    sources: ~
    name: handlefiles-route
    snis: ~
    tags:
      - handlefiles
  - destinations: ~
    protocols:
      - http
      - https
    service: 70358580-7171-41af-8996-1a0bc9582e9a
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753945911
    updated_at: 1754142455
    id: bec1f54a-9502-403e-99d1-8f9b8bc31072
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/auth
    regex_priority: 0
    headers: ~
    sources: ~
    name: auth-route
    snis: ~
    tags:
      - auth
  - destinations: ~
    protocols:
      - http
      - https
    service: 0929d3ca-7920-4c59-885f-7627bb7b751c
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753946004
    updated_at: 1754142465
    id: d18d884d-ff52-4651-80d9-ff8f1c9ef9a1
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/booking
    regex_priority: 0
    headers: ~
    sources: ~
    name: booking-route
    snis: ~
    tags:
      - booking
  - destinations: ~
    protocols:
      - http
      - https
    service: a2320f4b-c669-4103-b066-d66b3110e1b3
    methods: ~
    https_redirect_status_code: 426
    strip_path: true
    path_handling: v0
    request_buffering: true
    response_buffering: true
    created_at: 1753946098
    updated_at: 1754142673
    id: f796aace-45dd-4496-a5f3-4e44de2eb3f6
    hosts: ~
    preserve_host: false
    paths:
      - /v1/api/layouts
    regex_priority: 0
    headers: ~
    sources: ~
    name: cms-route
    snis: ~
    tags:
      - cms
plugins:
  - id: 5fea785e-4f27-4b90-a556-a2cafae7732b
    service: f2bfbbf7-f020-432b-b33f-33cad7554524
    instance_name: ~
    updated_at: 1754145191
    route: 5e0e3004-3248-4e4c-adb6-fc8184ba3b12
    enabled: true
    protocols:
      - grpc
      - grpcs
      - http
      - https
    config:
      maximum_expiration: 86400
      header_names:
        - authorization
      uri_param_names:
        - jwt
      cookie_names: []
      key_claim_name: iss
      anonymous: ~
      secret_is_base64: false
      realm: ~
      claims_to_verify:
        - exp
      run_on_preflight: true
    name: jwt
    tags: ~
    created_at: 1754143478
    consumer: ~
  - id: 9387f21c-d238-4f3b-b3da-121b7404c770
    service: ~
    instance_name: ~
    updated_at: 1754288688
    route: f796aace-45dd-4496-a5f3-4e44de2eb3f6
    enabled: true
    protocols:
      - grpc
      - grpcs
      - http
      - https
    config:
      header_name: Kong-Request-ID
      echo_downstream: false
      generator: uuid#counter
    name: correlation-id
    tags: ~
    created_at: 1754288688
    consumer: ~
  - id: 93ebbfd0-ed41-4d07-9d7b-c7f7ec958677
    service: ~
    instance_name: ~
    updated_at: 1754287174
    route: f796aace-45dd-4496-a5f3-4e44de2eb3f6
    enabled: true
    protocols:
      - grpc
      - grpcs
      - http
      - https
    config:
      redis_timeout: 2000
      redis_host: ~
      redis_database: 0
      redis_server_name: ~
      second: ~
      limit_by: consumer
      minute: 5
      fault_tolerant: true
      day: ~
      hide_client_headers: false
      year: ~
      error_code: 429
      error_message: API rate limit exceeded
      header_name: ~
      redis_ssl_verify: false
      redis_port: 6379
      path: ~
      redis:
        host: ~
        port: 6379
        timeout: 2000
        database: 0
        username: ~
        ssl_verify: false
        ssl: false
        password: ~
        server_name: ~
      hour: ~
      redis_username: ~
      redis_password: ~
      redis_ssl: false
      policy: local
      sync_rate: -1
      month: ~
    name: rate-limiting
    tags: ~
    created_at: 1754287174
    consumer: ~
  - id: f6731b4e-aee4-4aa4-ab4f-43c41bd773d9
    service: ~
    instance_name: ~
    updated_at: 1754288053
    route: f796aace-45dd-4496-a5f3-4e44de2eb3f6
    enabled: true
    protocols:
      - grpc
      - grpcs
      - http
      - https
    config:
      reopen: false
      custom_fields_by_lua: []
      path: /tmp/file.log
    name: file-log
    tags: ~
    created_at: 1754288053
    consumer: ~
jwt_secrets:
  - rsa_public_key: ~
    id: 926f9de6-78c3-46ea-abb0-5020b20651d2
    algorithm: HS256
    consumer: f85447cf-124c-4d29-a70d-b6b1024a47ef
    key: "{{KONG_KEY_SECRET}}"
    secret: "{{KONG_JWT_SECRET}}"
    created_at: 1754143555
    tags: ~
